HelloWorld.class: HelloWorld.java
	javac -classpath /home/jsiegel/repos/hue/java-sdk/QuickStartApp/libs/huelocalsdk.jar:/home/jsiegel/repos/hue/java-sdk/QuickStartApp/libs/sdkresources.jar HelloWorld.java
